// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/ai.dart';
import 'api/boxes.dart';
import 'api/categories.dart';
import 'api/db.dart';
import 'api/items.dart';
import 'api/model.dart';
import 'api/photos.dart';
import 'api/search.dart';
import 'api/settings.dart';
import 'api/units.dart';
import 'core/ai/apply.dart';
import 'core/ai/config.dart';
import 'core/ai/parse.dart';
import 'core/error.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<EmbedProgress> dco_decode_StreamSink_embed_progress_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AiConfig dco_decode_ai_config(dynamic raw);

  @protected
  AiProvider dco_decode_ai_provider(dynamic raw);

  @protected
  AiStatus dco_decode_ai_status(dynamic raw);

  @protected
  AiTestResult dco_decode_ai_test_result(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AiConfig dco_decode_box_autoadd_ai_config(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  EntityRef dco_decode_box_autoadd_entity_ref(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  ParsedIntent dco_decode_box_autoadd_parsed_intent(dynamic raw);

  @protected
  Category dco_decode_category(dynamic raw);

  @protected
  EmbedProgress dco_decode_embed_progress(dynamic raw);

  @protected
  EmbedProgressSummary dco_decode_embed_progress_summary(dynamic raw);

  @protected
  EntityRef dco_decode_entity_ref(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  FinditError dco_decode_findit_error(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  IntentKind dco_decode_intent_kind(dynamic raw);

  @protected
  Item dco_decode_item(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Category> dco_decode_list_category(dynamic raw);

  @protected
  List<Item> dco_decode_list_item(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SearchResult> dco_decode_list_search_result(dynamic raw);

  @protected
  List<StorageBox> dco_decode_list_storage_box(dynamic raw);

  @protected
  List<Unit> dco_decode_list_unit(dynamic raw);

  @protected
  MatchedBy dco_decode_matched_by(dynamic raw);

  @protected
  ModifyResult dco_decode_modify_result(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  EntityRef? dco_decode_opt_box_autoadd_entity_ref(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  Float32List? dco_decode_opt_list_prim_f_32_strict(dynamic raw);

  @protected
  Int64List? dco_decode_opt_list_prim_i_64_strict(dynamic raw);

  @protected
  ParsedIntent dco_decode_parsed_intent(dynamic raw);

  @protected
  QuickAddResult dco_decode_quick_add_result(dynamic raw);

  @protected
  SearchResult dco_decode_search_result(dynamic raw);

  @protected
  StorageBox dco_decode_storage_box(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  Unit dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<EmbedProgress> sse_decode_StreamSink_embed_progress_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AiConfig sse_decode_ai_config(SseDeserializer deserializer);

  @protected
  AiProvider sse_decode_ai_provider(SseDeserializer deserializer);

  @protected
  AiStatus sse_decode_ai_status(SseDeserializer deserializer);

  @protected
  AiTestResult sse_decode_ai_test_result(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AiConfig sse_decode_box_autoadd_ai_config(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  EntityRef sse_decode_box_autoadd_entity_ref(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  ParsedIntent sse_decode_box_autoadd_parsed_intent(
    SseDeserializer deserializer,
  );

  @protected
  Category sse_decode_category(SseDeserializer deserializer);

  @protected
  EmbedProgress sse_decode_embed_progress(SseDeserializer deserializer);

  @protected
  EmbedProgressSummary sse_decode_embed_progress_summary(
    SseDeserializer deserializer,
  );

  @protected
  EntityRef sse_decode_entity_ref(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  FinditError sse_decode_findit_error(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  IntentKind sse_decode_intent_kind(SseDeserializer deserializer);

  @protected
  Item sse_decode_item(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Category> sse_decode_list_category(SseDeserializer deserializer);

  @protected
  List<Item> sse_decode_list_item(SseDeserializer deserializer);

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SearchResult> sse_decode_list_search_result(
    SseDeserializer deserializer,
  );

  @protected
  List<StorageBox> sse_decode_list_storage_box(SseDeserializer deserializer);

  @protected
  List<Unit> sse_decode_list_unit(SseDeserializer deserializer);

  @protected
  MatchedBy sse_decode_matched_by(SseDeserializer deserializer);

  @protected
  ModifyResult sse_decode_modify_result(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  EntityRef? sse_decode_opt_box_autoadd_entity_ref(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  Float32List? sse_decode_opt_list_prim_f_32_strict(
    SseDeserializer deserializer,
  );

  @protected
  Int64List? sse_decode_opt_list_prim_i_64_strict(SseDeserializer deserializer);

  @protected
  ParsedIntent sse_decode_parsed_intent(SseDeserializer deserializer);

  @protected
  QuickAddResult sse_decode_quick_add_result(SseDeserializer deserializer);

  @protected
  SearchResult sse_decode_search_result(SseDeserializer deserializer);

  @protected
  StorageBox sse_decode_storage_box(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  Unit sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_embed_progress_Sse(
    RustStreamSink<EmbedProgress> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_ai_config(AiConfig self, SseSerializer serializer);

  @protected
  void sse_encode_ai_provider(AiProvider self, SseSerializer serializer);

  @protected
  void sse_encode_ai_status(AiStatus self, SseSerializer serializer);

  @protected
  void sse_encode_ai_test_result(AiTestResult self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ai_config(
    AiConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_entity_ref(
    EntityRef self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_parsed_intent(
    ParsedIntent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_category(Category self, SseSerializer serializer);

  @protected
  void sse_encode_embed_progress(EmbedProgress self, SseSerializer serializer);

  @protected
  void sse_encode_embed_progress_summary(
    EmbedProgressSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_entity_ref(EntityRef self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_findit_error(FinditError self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_intent_kind(IntentKind self, SseSerializer serializer);

  @protected
  void sse_encode_item(Item self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_category(List<Category> self, SseSerializer serializer);

  @protected
  void sse_encode_list_item(List<Item> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_64_strict(
    Int64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_search_result(
    List<SearchResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_storage_box(
    List<StorageBox> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_unit(List<Unit> self, SseSerializer serializer);

  @protected
  void sse_encode_matched_by(MatchedBy self, SseSerializer serializer);

  @protected
  void sse_encode_modify_result(ModifyResult self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_entity_ref(
    EntityRef? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_prim_f_32_strict(
    Float32List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_prim_i_64_strict(
    Int64List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_parsed_intent(ParsedIntent self, SseSerializer serializer);

  @protected
  void sse_encode_quick_add_result(
    QuickAddResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_search_result(SearchResult self, SseSerializer serializer);

  @protected
  void sse_encode_storage_box(StorageBox self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(Unit self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
