// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

@freezed
sealed class FinditError with _$FinditError implements FrbException {
  const FinditError._();

  /// 数据库尚未通过 `init_db` 初始化。
  const factory FinditError.dbNotInitialized() = FinditError_DbNotInitialized;

  /// 底层 SQLite / rusqlite 错误。
  const factory FinditError.db(String field0) = FinditError_Db;

  /// 唯一约束冲突（重名）。
  /// `entity` 表示实体种类（如 "存储单元" / "收纳箱" / "分类"）。
  const factory FinditError.duplicateName({
    required String entity,
    required String name,
  }) = FinditError_DuplicateName;

  /// 目标实体不存在。
  const factory FinditError.notFound({
    required String entity,
    required String hint,
  }) = FinditError_NotFound;

  /// 输入校验失败。
  const factory FinditError.validation(String field0) = FinditError_Validation;

  /// 文件 / 目录 IO 错误。
  const factory FinditError.io(String field0) = FinditError_Io;
}
