// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../core/ai/apply.dart';
import '../core/ai/config.dart';
import '../core/ai/parse.dart';
import '../core/error.dart';
import '../frb_generated.dart';
import 'model.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `ai_error_message`, `backfill_one_round`, `cache_test_result`, `fresh_cached_test`, `parse_via_ai`

/// 读取 AI 配置（缺失项以默认值补齐）。
Future<AiConfig> getAiConfig() => RustLib.instance.api.crateApiAiGetAiConfig();

/// 保存 AI 配置到 app_settings。服务地址不允许为空。
Future<bool> saveAiConfig({required AiConfig config}) =>
    RustLib.instance.api.crateApiAiSaveAiConfig(config: config);

/// 测试连接：对话与向量各探一次，返回各自可用性与错误信息。
/// 结果缓存 60 秒供 `get_ai_status` 复用。
Future<AiTestResult> testAiConnection() =>
    RustLib.instance.api.crateApiAiTestAiConnection();

/// AI 总体状态：配置概要 + 缓存探活结果（60 秒内不重探）。
Future<AiStatus> getAiStatus() => RustLib.instance.api.crateApiAiGetAiStatus();

/// 一句话 → 结构化意图（建档或修改，由模型判断）。
Future<ParsedIntent> parseQuickAdd({required String text}) =>
    RustLib.instance.api.crateApiAiParseQuickAdd(text: text);

/// 一句话 → 修改意图（与 `parse_quick_add` 同一解析链路）。
Future<ParsedIntent> parseAiModify({required String text}) =>
    RustLib.instance.api.crateApiAiParseAiModify(text: text);

/// 确认建档：单元/箱按名称自动创建或复用同名实体（单事务）。
Future<QuickAddResult> applyQuickAdd({required ParsedIntent intent}) =>
    RustLib.instance.api.crateApiAiApplyQuickAdd(intent: intent);

/// 确认修改：定位目标物品并应用变更（单事务）。
Future<ModifyResult> applyAiModify({required ParsedIntent intent}) =>
    RustLib.instance.api.crateApiAiApplyAiModify(intent: intent);

/// 生成搜索查询向量。未配置或任何失败均返回 `Ok(None)`，
/// 让上层降级为纯关键词搜索。
Future<Float32List?> generateQueryEmbedding({required String text}) =>
    RustLib.instance.api.crateApiAiGenerateQueryEmbedding(text: text);

/// 补齐待处理向量：扫描 `embedding IS NULL` 的物品，分批写入。
/// 返回本次处理条数。
///
/// 每轮三段式：锁内取一批待处理文本 → 释放锁后做网络调用 →
/// 锁内写回（写回前重查维度一致性）。网络期间全局锁不持有，
/// 不会冻结其它数据库操作；中断后重跑即可继续（以数据库为待办源）。
Future<int> backfillPendingEmbeddings() =>
    RustLib.instance.api.crateApiAiBackfillPendingEmbeddings();

/// 重建全部向量：清空后经 [`StreamSink`] 流式推送进度（done/total）。
/// Dart 端监听流；函数最终返回处理汇总。
/// 与 [`backfill_pending_embeddings`] 同样按三段式执行，网络调用不持锁。
Stream<EmbedProgress> rebuildEmbeddings() =>
    RustLib.instance.api.crateApiAiRebuildEmbeddings();
