// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../core/error.dart';
import '../frb_generated.dart';
import 'model.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `count_photo_files`, `count_rows`

/// 导出备份到 `target_path`（zip）。进度阶段：`snapshot` / `photos` /
/// `finalize`，最后一条 `done` 事件携带 [`BackupSummary`]。
Stream<BackupProgress> exportBackup({required String targetPath}) =>
    RustLib.instance.api.crateApiBackupExportBackup(targetPath: targetPath);

/// 从 `zip_path` 恢复备份：关闭当前连接 → 校验/解压/原子替换 →
/// 重新初始化数据库（迁移幂等）。进度阶段：`validate` / `extract` /
/// `swap`，最后一条 `done` 事件携带 [`RestoreSummary`]。
///
/// 恢复失败时正式数据目录不会被破坏，且会尽力重新打开原库。
Stream<RestoreProgress> restoreBackup({required String zipPath}) =>
    RustLib.instance.api.crateApiBackupRestoreBackup(zipPath: zipPath);
