// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../core/error.dart';
import '../frb_generated.dart';
import 'model.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<StorageBox> createBox({
  required PlatformInt64 unitId,
  required String name,
  required String description,
}) => RustLib.instance.api.crateApiBoxesCreateBox(
  unitId: unitId,
  name: name,
  description: description,
);

Future<List<StorageBox>> listBoxes({required PlatformInt64 unitId}) =>
    RustLib.instance.api.crateApiBoxesListBoxes(unitId: unitId);

Future<StorageBox> getBox({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiBoxesGetBox(id: id);

Future<StorageBox> getBoxBySlug({required String slug}) =>
    RustLib.instance.api.crateApiBoxesGetBoxBySlug(slug: slug);

Future<StorageBox> updateBox({
  required PlatformInt64 id,
  String? name,
  String? description,
  PlatformInt64? unitId,
}) => RustLib.instance.api.crateApiBoxesUpdateBox(
  id: id,
  name: name,
  description: description,
  unitId: unitId,
);

Future<bool> deleteBox({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiBoxesDeleteBox(id: id);
