// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../core/error.dart';
import '../frb_generated.dart';
import 'model.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<Category> createCategory({required String name}) =>
    RustLib.instance.api.crateApiCategoriesCreateCategory(name: name);

Future<List<Category>> listCategories() =>
    RustLib.instance.api.crateApiCategoriesListCategories();

Future<Category> renameCategory({
  required PlatformInt64 id,
  required String newName,
}) => RustLib.instance.api.crateApiCategoriesRenameCategory(
  id: id,
  newName: newName,
);

Future<bool> deleteCategory({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiCategoriesDeleteCategory(id: id);
