// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../core/error.dart';
import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 打开（或创建）数据库并应用迁移。`db_dir` 为存放 `findit.db` 的目录。
/// 由 Dart 侧在 `RustLib.init()` 之后、调用其他 API 之前调用。
/// 返回 `true` 表示成功（FRB 异步接口不支持空返回，用 bool 占位）。
Future<bool> initDb({required String dbDir}) =>
    RustLib.instance.api.crateApiDbInitDb(dbDir: dbDir);
