// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../core/error.dart';
import '../frb_generated.dart';
import 'model.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<Item> createItem({
  required PlatformInt64 boxId,
  required String name,
  required String description,
  required PlatformInt64 quantity,
  required Int64List categoryIds,
}) => RustLib.instance.api.crateApiItemsCreateItem(
  boxId: boxId,
  name: name,
  description: description,
  quantity: quantity,
  categoryIds: categoryIds,
);

Future<List<Item>> listItems({required PlatformInt64 boxId}) =>
    RustLib.instance.api.crateApiItemsListItems(boxId: boxId);

Future<Item> getItem({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiItemsGetItem(id: id);

Future<Item> updateItem({
  required PlatformInt64 id,
  String? name,
  String? description,
  PlatformInt64? quantity,
  PlatformInt64? boxId,
  Int64List? categoryIds,
}) => RustLib.instance.api.crateApiItemsUpdateItem(
  id: id,
  name: name,
  description: description,
  quantity: quantity,
  boxId: boxId,
  categoryIds: categoryIds,
);

Future<bool> deleteItem({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiItemsDeleteItem(id: id);
