// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

/// 分类。
class Category {
  final PlatformInt64 id;
  final String name;

  const Category({required this.id, required this.name});

  @override
  int get hashCode => id.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Category &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name;
}

/// 物品（放在某个收纳箱内）。不含 `embedding`。
class Item {
  final PlatformInt64 id;
  final String name;
  final String description;
  final PlatformInt64 quantity;

  /// 照片相对路径；未上传照片时为 `None`。
  final String? photoPath;
  final PlatformInt64 boxId;

  /// 物品所属分类名列表。
  final List<String> categories;

  /// ISO 8601 UTC 字符串。
  final String createdAt;

  /// ISO 8601 UTC 字符串。
  final String updatedAt;

  const Item({
    required this.id,
    required this.name,
    required this.description,
    required this.quantity,
    this.photoPath,
    required this.boxId,
    required this.categories,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      description.hashCode ^
      quantity.hashCode ^
      photoPath.hashCode ^
      boxId.hashCode ^
      categories.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Item &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          description == other.description &&
          quantity == other.quantity &&
          photoPath == other.photoPath &&
          boxId == other.boxId &&
          categories == other.categories &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

/// 收纳箱（挂在某个存储单元下，`slug` 用于二维码）。
/// 命名加 `Storage` 前缀以避免与 `std::boxed::Box` 冲突。
class StorageBox {
  final PlatformInt64 id;

  /// UUID v4，建箱时生成，用于二维码内容。
  final String slug;
  final String name;
  final String description;
  final PlatformInt64 unitId;

  /// 该箱内物品数量。
  final PlatformInt64 itemCount;

  /// ISO 8601 UTC 字符串。
  final String createdAt;

  /// ISO 8601 UTC 字符串。
  final String updatedAt;

  const StorageBox({
    required this.id,
    required this.slug,
    required this.name,
    required this.description,
    required this.unitId,
    required this.itemCount,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      slug.hashCode ^
      name.hashCode ^
      description.hashCode ^
      unitId.hashCode ^
      itemCount.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StorageBox &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          slug == other.slug &&
          name == other.name &&
          description == other.description &&
          unitId == other.unitId &&
          itemCount == other.itemCount &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

/// 存储单元（如“客厅柜子”“储藏室货架”）。
class Unit {
  final PlatformInt64 id;
  final String name;
  final String description;

  /// 该单元下的收纳箱数量。
  final PlatformInt64 boxCount;

  const Unit({
    required this.id,
    required this.name,
    required this.description,
    required this.boxCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ description.hashCode ^ boxCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Unit &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          description == other.description &&
          boxCount == other.boxCount;
}
