// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../core/ai/config.dart';
import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// AI 总体状态：配置概要 + 短缓存的探活结果。
class AiStatus {
  /// 服务地址非空即视为已配置。
  final bool configured;
  final AiProvider provider;
  final String baseUrl;
  final String chatModel;
  final String embedModel;

  /// 库存向量实际使用的模型名（未回填过为 `None`）。
  final String? embeddedModel;

  /// 库存向量维度。
  final PlatformInt64? embeddedDim;

  /// 待回填物品数。
  final PlatformInt64 pendingEmbeddings;

  /// 缓存探活：对话可用性（未探活为 `None`）。
  final bool? lastChatOk;

  /// 缓存探活：向量可用性。
  final bool? lastEmbedOk;

  /// 缓存探活距今秒数（无缓存为 `None`）。
  final PlatformInt64? cacheAgeSecs;

  const AiStatus({
    required this.configured,
    required this.provider,
    required this.baseUrl,
    required this.chatModel,
    required this.embedModel,
    this.embeddedModel,
    this.embeddedDim,
    required this.pendingEmbeddings,
    this.lastChatOk,
    this.lastEmbedOk,
    this.cacheAgeSecs,
  });

  @override
  int get hashCode =>
      configured.hashCode ^
      provider.hashCode ^
      baseUrl.hashCode ^
      chatModel.hashCode ^
      embedModel.hashCode ^
      embeddedModel.hashCode ^
      embeddedDim.hashCode ^
      pendingEmbeddings.hashCode ^
      lastChatOk.hashCode ^
      lastEmbedOk.hashCode ^
      cacheAgeSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiStatus &&
          runtimeType == other.runtimeType &&
          configured == other.configured &&
          provider == other.provider &&
          baseUrl == other.baseUrl &&
          chatModel == other.chatModel &&
          embedModel == other.embedModel &&
          embeddedModel == other.embeddedModel &&
          embeddedDim == other.embeddedDim &&
          pendingEmbeddings == other.pendingEmbeddings &&
          lastChatOk == other.lastChatOk &&
          lastEmbedOk == other.lastEmbedOk &&
          cacheAgeSecs == other.cacheAgeSecs;
}

/// AI 连接探活结果：对话与向量各自可用性 + 错误信息。
class AiTestResult {
  final bool chatOk;
  final String chatMessage;
  final bool embedOk;
  final String embedMessage;

  const AiTestResult({
    required this.chatOk,
    required this.chatMessage,
    required this.embedOk,
    required this.embedMessage,
  });

  @override
  int get hashCode =>
      chatOk.hashCode ^
      chatMessage.hashCode ^
      embedOk.hashCode ^
      embedMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiTestResult &&
          runtimeType == other.runtimeType &&
          chatOk == other.chatOk &&
          chatMessage == other.chatMessage &&
          embedOk == other.embedOk &&
          embedMessage == other.embedMessage;
}

/// 备份导出进度（流式推送）。
///
/// `stage` ∈ `snapshot` / `photos` / `finalize` / `done`；
/// 最后一条事件（`stage == "done"`）携带完整 [`BackupSummary`]
/// （FRB 的流式函数返回值不会到达 Dart，故随流下发）。
class BackupProgress {
  final String stage;
  final int done;
  final int total;
  final BackupSummary? summary;

  const BackupProgress({
    required this.stage,
    required this.done,
    required this.total,
    this.summary,
  });

  @override
  int get hashCode =>
      stage.hashCode ^ done.hashCode ^ total.hashCode ^ summary.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackupProgress &&
          runtimeType == other.runtimeType &&
          stage == other.stage &&
          done == other.done &&
          total == other.total &&
          summary == other.summary;
}

/// 备份导出汇总。
class BackupSummary {
  final PlatformInt64 itemsCount;
  final PlatformInt64 boxesCount;
  final PlatformInt64 unitsCount;

  /// 打进 zip 的照片文件数（含缩略图）。
  final int photosCount;

  /// zip 内未压缩总字节数。
  final PlatformInt64 totalBytes;

  /// 实际写入的备份文件路径。
  final String path;

  const BackupSummary({
    required this.itemsCount,
    required this.boxesCount,
    required this.unitsCount,
    required this.photosCount,
    required this.totalBytes,
    required this.path,
  });

  @override
  int get hashCode =>
      itemsCount.hashCode ^
      boxesCount.hashCode ^
      unitsCount.hashCode ^
      photosCount.hashCode ^
      totalBytes.hashCode ^
      path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackupSummary &&
          runtimeType == other.runtimeType &&
          itemsCount == other.itemsCount &&
          boxesCount == other.boxesCount &&
          unitsCount == other.unitsCount &&
          photosCount == other.photosCount &&
          totalBytes == other.totalBytes &&
          path == other.path;
}

/// 分类。
class Category {
  final PlatformInt64 id;
  final String name;

  const Category({required this.id, required this.name});

  @override
  int get hashCode => id.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Category &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name;
}

/// 向量重建进度（流式推送）。
class EmbedProgress {
  final int done;
  final int total;

  const EmbedProgress({required this.done, required this.total});

  @override
  int get hashCode => done.hashCode ^ total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EmbedProgress &&
          runtimeType == other.runtimeType &&
          done == other.done &&
          total == other.total;
}

/// 向量重建汇总。
class EmbedProgressSummary {
  final int processed;
  final int total;

  const EmbedProgressSummary({required this.processed, required this.total});

  @override
  int get hashCode => processed.hashCode ^ total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EmbedProgressSummary &&
          runtimeType == other.runtimeType &&
          processed == other.processed &&
          total == other.total;
}

/// 物品（放在某个收纳箱内）。不含 `embedding`。
class Item {
  final PlatformInt64 id;
  final String name;
  final String description;
  final PlatformInt64 quantity;

  /// 照片相对路径；未上传照片时为 `None`。
  final String? photoPath;
  final PlatformInt64 boxId;

  /// 物品所属分类名列表。
  final List<String> categories;

  /// ISO 8601 UTC 字符串。
  final String createdAt;

  /// ISO 8601 UTC 字符串。
  final String updatedAt;

  const Item({
    required this.id,
    required this.name,
    required this.description,
    required this.quantity,
    this.photoPath,
    required this.boxId,
    required this.categories,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      description.hashCode ^
      quantity.hashCode ^
      photoPath.hashCode ^
      boxId.hashCode ^
      categories.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Item &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          description == other.description &&
          quantity == other.quantity &&
          photoPath == other.photoPath &&
          boxId == other.boxId &&
          categories == other.categories &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

/// 搜索命中方式。
enum MatchedBy {
  /// 语义向量命中，附带相似度百分比。
  semantic,

  /// 关键词命中。
  keyword,
}

/// 备份恢复进度（流式推送）。
///
/// `stage` ∈ `validate` / `extract` / `swap` / `done`；
/// 最后一条事件（`stage == "done"`）携带完整 [`RestoreSummary`]。
class RestoreProgress {
  final String stage;
  final int done;
  final int total;
  final RestoreSummary? summary;

  const RestoreProgress({
    required this.stage,
    required this.done,
    required this.total,
    this.summary,
  });

  @override
  int get hashCode =>
      stage.hashCode ^ done.hashCode ^ total.hashCode ^ summary.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RestoreProgress &&
          runtimeType == other.runtimeType &&
          stage == other.stage &&
          done == other.done &&
          total == other.total &&
          summary == other.summary;
}

/// 备份恢复汇总。
class RestoreSummary {
  /// 恢复成功标记：Dart 侧据此提示并刷新全部页面数据。
  final bool restored;

  /// 恢复后库中的库存计数。
  final PlatformInt64 itemsCount;
  final PlatformInt64 boxesCount;
  final PlatformInt64 unitsCount;

  /// 恢复的照片文件数（含缩略图）。
  final int photosCount;

  const RestoreSummary({
    required this.restored,
    required this.itemsCount,
    required this.boxesCount,
    required this.unitsCount,
    required this.photosCount,
  });

  @override
  int get hashCode =>
      restored.hashCode ^
      itemsCount.hashCode ^
      boxesCount.hashCode ^
      unitsCount.hashCode ^
      photosCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RestoreSummary &&
          runtimeType == other.runtimeType &&
          restored == other.restored &&
          itemsCount == other.itemsCount &&
          boxesCount == other.boxesCount &&
          unitsCount == other.unitsCount &&
          photosCount == other.photosCount;
}

/// 一条搜索结果：物品完整信息 + 所在箱/单元名 + 命中方式。
class SearchResult {
  final PlatformInt64 id;
  final String name;
  final String description;
  final PlatformInt64 quantity;

  /// 照片相对路径；未上传照片时为 `None`。
  final String? photoPath;
  final PlatformInt64 boxId;

  /// 物品所属分类名列表。
  final List<String> categories;

  /// 所在收纳箱名（便于结果定位）。
  final String boxName;

  /// 所在存储单元名（便于结果定位）。
  final String unitName;
  final MatchedBy matchedBy;

  /// 语义命中时的相似度百分比（0-100）；关键词命中为 `None`。
  final int? similarityPercent;

  const SearchResult({
    required this.id,
    required this.name,
    required this.description,
    required this.quantity,
    this.photoPath,
    required this.boxId,
    required this.categories,
    required this.boxName,
    required this.unitName,
    required this.matchedBy,
    this.similarityPercent,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      description.hashCode ^
      quantity.hashCode ^
      photoPath.hashCode ^
      boxId.hashCode ^
      categories.hashCode ^
      boxName.hashCode ^
      unitName.hashCode ^
      matchedBy.hashCode ^
      similarityPercent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchResult &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          description == other.description &&
          quantity == other.quantity &&
          photoPath == other.photoPath &&
          boxId == other.boxId &&
          categories == other.categories &&
          boxName == other.boxName &&
          unitName == other.unitName &&
          matchedBy == other.matchedBy &&
          similarityPercent == other.similarityPercent;
}

/// 收纳箱（挂在某个存储单元下，`slug` 用于二维码）。
/// 命名加 `Storage` 前缀以避免与 `std::boxed::Box` 冲突。
class StorageBox {
  final PlatformInt64 id;

  /// UUID v4，建箱时生成，用于二维码内容。
  final String slug;
  final String name;
  final String description;
  final PlatformInt64 unitId;

  /// 该箱内物品数量。
  final PlatformInt64 itemCount;

  /// ISO 8601 UTC 字符串。
  final String createdAt;

  /// ISO 8601 UTC 字符串。
  final String updatedAt;

  const StorageBox({
    required this.id,
    required this.slug,
    required this.name,
    required this.description,
    required this.unitId,
    required this.itemCount,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      slug.hashCode ^
      name.hashCode ^
      description.hashCode ^
      unitId.hashCode ^
      itemCount.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StorageBox &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          slug == other.slug &&
          name == other.name &&
          description == other.description &&
          unitId == other.unitId &&
          itemCount == other.itemCount &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

/// 存储单元（如“客厅柜子”“储藏室货架”）。
class Unit {
  final PlatformInt64 id;
  final String name;
  final String description;

  /// 该单元下的收纳箱数量。
  final PlatformInt64 boxCount;

  const Unit({
    required this.id,
    required this.name,
    required this.description,
    required this.boxCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ description.hashCode ^ boxCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Unit &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          description == other.description &&
          boxCount == other.boxCount;
}
