// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../core/error.dart';
import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 保存物品照片：压缩（主图 1600px/q82 + 缩略图 256px/q70）落盘，
/// 更新 `items.photo_path` 并清理旧照片文件。返回新主图文件名。
Future<String> saveItemPhoto({
  required PlatformInt64 itemId,
  required List<int> bytes,
}) => RustLib.instance.api.crateApiPhotosSaveItemPhoto(
  itemId: itemId,
  bytes: bytes,
);

/// 删除物品照片：清空 `photo_path` 并移除主图与缩略图文件。
Future<bool> deleteItemPhoto({required PlatformInt64 itemId}) =>
    RustLib.instance.api.crateApiPhotosDeleteItemPhoto(itemId: itemId);

/// 主图文件的完整本地路径（入参为 `items.photo_path`）。
Future<String> getPhotoFullPath({required String fileName}) =>
    RustLib.instance.api.crateApiPhotosGetPhotoFullPath(fileName: fileName);

/// 缩略图文件的完整本地路径（入参为主图文件名）。
Future<String> getThumbFullPath({required String fileName}) =>
    RustLib.instance.api.crateApiPhotosGetThumbFullPath(fileName: fileName);
