// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../core/error.dart';
import '../frb_generated.dart';
import 'model.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 双通道搜索。
///
/// `embedding` 为查询向量（由调用方生成）；`None` 时只做关键词搜索。
/// 语义命中在前并附带相似度百分比，关键词命中在后。
Future<List<SearchResult>> searchItems({
  required String query,
  Float32List? embedding,
}) => RustLib.instance.api.crateApiSearchSearchItems(
  query: query,
  embedding: embedding,
);
