// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../core/error.dart';
import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 读取设置项；不存在返回 `null`。
Future<String?> getSetting({required String key}) =>
    RustLib.instance.api.crateApiSettingsGetSetting(key: key);

/// 写入设置项（存在则覆盖）。返回 `true` 表示成功（FRB 异步接口不支持空返回）。
Future<bool> setSetting({required String key, required String value}) =>
    RustLib.instance.api.crateApiSettingsSetSetting(key: key, value: value);
