// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../core/error.dart';
import '../frb_generated.dart';
import 'model.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<Unit> createUnit({required String name, required String description}) =>
    RustLib.instance.api.crateApiUnitsCreateUnit(
      name: name,
      description: description,
    );

Future<List<Unit>> listUnits() => RustLib.instance.api.crateApiUnitsListUnits();

Future<Unit> getUnit({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiUnitsGetUnit(id: id);

Future<Unit> updateUnit({
  required PlatformInt64 id,
  String? name,
  String? description,
}) => RustLib.instance.api.crateApiUnitsUpdateUnit(
  id: id,
  name: name,
  description: description,
);

Future<bool> deleteUnit({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiUnitsDeleteUnit(id: id);
