// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../api/model.dart';
import '../../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 实体引用：id + 名称 + 是否本次新建。
class EntityRef {
  final PlatformInt64 id;
  final String name;
  final bool created;

  const EntityRef({
    required this.id,
    required this.name,
    required this.created,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ created.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntityRef &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          created == other.created;
}

/// 修改结果：更新后的物品、变更到的收纳箱（无移动为 `None`）与已应用变更描述。
class ModifyResult {
  final Item item;
  final EntityRef? movedBox;
  final List<String> changes;

  const ModifyResult({
    required this.item,
    this.movedBox,
    required this.changes,
  });

  @override
  int get hashCode => item.hashCode ^ movedBox.hashCode ^ changes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModifyResult &&
          runtimeType == other.runtimeType &&
          item == other.item &&
          movedBox == other.movedBox &&
          changes == other.changes;
}

/// 建档结果：单元、收纳箱（含新建/复用标记）与入库物品。
class QuickAddResult {
  final EntityRef unit;
  final EntityRef storageBox;
  final Item item;

  const QuickAddResult({
    required this.unit,
    required this.storageBox,
    required this.item,
  });

  @override
  int get hashCode => unit.hashCode ^ storageBox.hashCode ^ item.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QuickAddResult &&
          runtimeType == other.runtimeType &&
          unit == other.unit &&
          storageBox == other.storageBox &&
          item == other.item;
}
