// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// AI 服务配置快照。
class AiConfig {
  final AiProvider provider;
  final String baseUrl;

  /// 仅 OpenAI 兼容接口使用；Ollama 留空。
  final String apiKey;
  final String chatModel;
  final String embedModel;

  /// 向量服务独立配置；为空时回退对话服务对应字段。
  final AiProvider embedProvider;
  final String embedBaseUrl;
  final String embedApiKey;

  const AiConfig({
    required this.provider,
    required this.baseUrl,
    required this.apiKey,
    required this.chatModel,
    required this.embedModel,
    required this.embedProvider,
    required this.embedBaseUrl,
    required this.embedApiKey,
  });

  /// 向量实际使用的 Provider（独立配置为空时回退对话 Provider）。
  AiProvider get effectiveEmbedProvider =>
      embedBaseUrl.trim().isEmpty ? provider : embedProvider;

  /// 向量实际使用的服务地址。
  String get effectiveEmbedBaseUrl =>
      embedBaseUrl.trim().isEmpty ? baseUrl : embedBaseUrl;

  /// 向量实际使用的 API Key。
  String get effectiveEmbedApiKey =>
      embedBaseUrl.trim().isEmpty ? apiKey : embedApiKey;

  /// 向量服务是否独立配置。
  bool get hasSeparateEmbedService => embedBaseUrl.trim().isNotEmpty;

  @override
  int get hashCode =>
      provider.hashCode ^
      baseUrl.hashCode ^
      apiKey.hashCode ^
      chatModel.hashCode ^
      embedModel.hashCode ^
      embedProvider.hashCode ^
      embedBaseUrl.hashCode ^
      embedApiKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiConfig &&
          runtimeType == other.runtimeType &&
          provider == other.provider &&
          baseUrl == other.baseUrl &&
          apiKey == other.apiKey &&
          chatModel == other.chatModel &&
          embedModel == other.embedModel &&
          embedProvider == other.embedProvider &&
          embedBaseUrl == other.embedBaseUrl &&
          embedApiKey == other.embedApiKey;
}

/// 支持的 AI 服务提供方。
enum AiProvider {
  /// 局域网 Ollama（`/api/chat` + `/api/embed`）。
  ollama,

  /// OpenAI 兼容接口（`/v1/chat/completions` + `/v1/embeddings`）。
  openAi,
}
