// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// AI 服务配置快照。
class AiConfig {
  final AiProvider provider;
  final String baseUrl;

  /// 仅 OpenAI 兼容接口使用；Ollama 留空。
  final String apiKey;
  final String chatModel;
  final String embedModel;

  const AiConfig({
    required this.provider,
    required this.baseUrl,
    required this.apiKey,
    required this.chatModel,
    required this.embedModel,
  });

  @override
  int get hashCode =>
      provider.hashCode ^
      baseUrl.hashCode ^
      apiKey.hashCode ^
      chatModel.hashCode ^
      embedModel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiConfig &&
          runtimeType == other.runtimeType &&
          provider == other.provider &&
          baseUrl == other.baseUrl &&
          apiKey == other.apiKey &&
          chatModel == other.chatModel &&
          embedModel == other.embedModel;
}

/// 支持的 AI 服务提供方。
enum AiProvider {
  /// 局域网 Ollama（`/api/chat` + `/api/embed`）。
  ollama,

  /// OpenAI 兼容接口（`/v1/chat/completions` + `/v1/embeddings`）。
  openAi,
}
