// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 意图类型。
enum IntentKind {
  /// 新建物品入档。
  createItem,

  /// 修改已有物品（移动、改名、改数量、改备注）。
  modifyItem,
}

/// 解析出的结构化意图。
///
/// 同时作为「确认应用」的输入：UI 预览时可修正任意字段后原样传回。
/// 建档场景使用 `unit_name/box_name/item_*` 字段；
/// 修改场景使用 `target_query` + `new_*` 字段（`None` 表示不变）。
class ParsedIntent {
  final IntentKind intent;

  /// 建档：目标存储单元名（可空，自动推导或创建默认单元）。
  final String? unitName;

  /// 建档：目标收纳箱名（必填，同名箱会被复用）。
  final String? boxName;

  /// 建档：物品名（必填）。
  final String? itemName;

  /// 建档：物品备注。
  final String? itemDescription;

  /// 建档：数量（≥1）。
  final PlatformInt64? quantity;

  /// 修改：目标物品的查询描述（按关键词搜索定位）。
  final String? targetQuery;

  /// 修改：移入的存储单元名（可空）。
  final String? newUnitName;

  /// 修改：移入的收纳箱名（同名复用，不存在则创建）。
  final String? newBoxName;

  /// 修改：新物品名。
  final String? newItemName;

  /// 修改：新备注。
  final String? newDescription;

  /// 修改：新数量（≥1）。
  final PlatformInt64? newQuantity;

  const ParsedIntent({
    required this.intent,
    this.unitName,
    this.boxName,
    this.itemName,
    this.itemDescription,
    this.quantity,
    this.targetQuery,
    this.newUnitName,
    this.newBoxName,
    this.newItemName,
    this.newDescription,
    this.newQuantity,
  });

  @override
  int get hashCode =>
      intent.hashCode ^
      unitName.hashCode ^
      boxName.hashCode ^
      itemName.hashCode ^
      itemDescription.hashCode ^
      quantity.hashCode ^
      targetQuery.hashCode ^
      newUnitName.hashCode ^
      newBoxName.hashCode ^
      newItemName.hashCode ^
      newDescription.hashCode ^
      newQuantity.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ParsedIntent &&
          runtimeType == other.runtimeType &&
          intent == other.intent &&
          unitName == other.unitName &&
          boxName == other.boxName &&
          itemName == other.itemName &&
          itemDescription == other.itemDescription &&
          quantity == other.quantity &&
          targetQuery == other.targetQuery &&
          newUnitName == other.newUnitName &&
          newBoxName == other.newBoxName &&
          newItemName == other.newItemName &&
          newDescription == other.newDescription &&
          newQuantity == other.newQuantity;
}
